package signaling

import (
	"crypto/sha256"
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// uuidV4Shape is what every RoomIDFromToken answer must look like: lowercase
// 8-4-4-4-12 hex with the version nibble 4 and the variant bits 10 (8, 9, a
// or b), which the server's case-insensitive UUID_REGEX also accepts.
var uuidV4Shape = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`)

// derivationVectors is testdata/derivation-vectors.json: generated by an
// independent Node one-liner from the spec 04 5.3 formula before this
// package had any derivation code (WP-B commit 1), and read in place by the
// server's T27 as well. A copy sits at
// work/14-test-evidence/S1-SRV-02/derivation-vectors.json in the plan folder.
type derivationVectors struct {
	Vectors []struct {
		HostToken string `json:"hostToken"`
		RoomID    string `json:"roomId"`
	} `json:"vectors"`
}

func loadDerivationVectors(t testing.TB) derivationVectors {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "derivation-vectors.json"))
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var v derivationVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(v.Vectors) != 3 {
		t.Fatalf("vectors file has %d vectors, want 3", len(v.Vectors))
	}
	return v
}

// The three server vectors (S1-SRV-02a T27). A failure names the vector by
// index and prints room ids only: tokens are never printed, even test ones.
func TestRoomIDFromTokenVectors(t *testing.T) {
	v := loadDerivationVectors(t)
	fixed := []string{strings.Repeat("A", 43), strings.Repeat("z_-", 14) + "Q"}
	for i, want := range fixed {
		if sha256.Sum256([]byte(v.Vectors[i].HostToken)) != sha256.Sum256([]byte(want)) {
			t.Fatalf("vector %d is not the fixed token the card names", i)
		}
	}
	for i, vec := range v.Vectors {
		if !uuidV4Shape.MatchString(vec.RoomID) {
			t.Fatalf("vector %d: the file's roomId %q is not a lowercase v4 UUID", i, vec.RoomID)
		}
		if got := RoomIDFromToken(vec.HostToken); got != vec.RoomID {
			t.Errorf("vector %d: RoomIDFromToken = %q, want %q", i, got, vec.RoomID)
		}
	}
}

// A token of any other shape derives nothing, so a caller can never build a
// link, or a join, around a room id the server would refuse.
func TestRoomIDFromTokenRefusesMalformedTokens(t *testing.T) {
	good := strings.Repeat("A", 43)
	for name, tok := range map[string]string{
		"empty":            "",
		"42 characters":    good[:42],
		"44 characters":    good + "A",
		"padding":          good[:42] + "=",
		"plus and slash":   good[:41] + "+/",
		"space":            good[:42] + " ",
		"trailing newline": good + "\n",
		"leading newline":  "\n" + good,
		"non-ASCII":        good[:42] + "é",
		"NUL":              good[:42] + "\x00",
	} {
		if got := RoomIDFromToken(tok); got != "" {
			t.Errorf("%s: RoomIDFromToken = %q, want \"\"", name, got)
		}
	}
}

// 43 characters, the regexp's shape, 1000 distinct samples. Distinctness is
// checked on digests, the way every token comparison here is made.
func TestNewHostTokenShape(t *testing.T) {
	seen := make(map[[32]byte]bool, 1000)
	for i := 0; i < 1000; i++ {
		tok, err := NewHostToken()
		if err != nil {
			t.Fatalf("NewHostToken: %v", err)
		}
		if len(tok) != 43 {
			t.Fatalf("sample %d has %d characters, want 43", i, len(tok))
		}
		if !HostTokenRegexp.MatchString(tok) {
			t.Fatalf("sample %d does not match HostTokenRegexp", i)
		}
		if !uuidV4Shape.MatchString(RoomIDFromToken(tok)) {
			t.Fatalf("sample %d derives no v4 room id", i)
		}
		d := sha256.Sum256([]byte(tok))
		if seen[d] {
			t.Fatalf("sample %d repeats an earlier token", i)
		}
		seen[d] = true
	}
}

func TestNewLinkIDShape(t *testing.T) {
	shape := regexp.MustCompile(`^[A-Za-z0-9_-]{11}$`)
	seen := make(map[string]bool, 1000)
	for i := 0; i < 1000; i++ {
		id, err := NewLinkID()
		if err != nil {
			t.Fatalf("NewLinkID: %v", err)
		}
		if len(id) != 11 || !shape.MatchString(id) {
			t.Fatalf("link id %q is not 11 base64url characters", id)
		}
		if seen[id] {
			t.Fatalf("link id %q repeated within 1000 samples", id)
		}
		seen[id] = true
	}
}
