name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Describe the feature or improvement.
      placeholder: It would be great if...
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why would this be useful?
      description: Explain how this would help you or other users.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you thought of any other ways to solve this?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other information, screenshots, or examples.
    validations:
      required: false
