/**
 * The pinned Floe Desktop release: single source of truth for every download
 * link on the site.
 *
 * The desktop app releases on its own desktop-v* tag series, separate from the
 * CLI's v* tags, and always as a GitHub pre-release with make_latest false, so
 * GitHub's /releases/latest permalinks can NEVER reach it (they resolve to the
 * CLI release, on purpose: the install scripts, `floe update`, and the
 * back-compat CI job all depend on that). Links must therefore pin an explicit
 * tag; asset URLs are fully deterministic from the version alone.
 *
 * Bump DESKTOP_VERSION when a new desktop release ships. A stale pin is never a
 * broken link, because release assets are immutable.
 */

// Bump these two together on every desktop release.
export const DESKTOP_VERSION = '0.2.1';
export const DESKTOP_RELEASE_DATE = 'Aug 2, 2026';

/**
 * The Microsoft Store listing: the primary Windows install path. The Store
 * build is re-signed by Microsoft, so it installs with no SmartScreen warning
 * and updates automatically; the GitHub assets below remain the fallback for
 * machines without Store access. The https URL works in any browser on any
 * OS (the ms-windows-store: protocol form does not, so it is not used).
 * The listing went public on 2026-08-02; winget resolves it too, as
 * `winget install --id 9NBQ8ZQ1065L --source msstore`.
 */
export const DESKTOP_STORE_ID = '9NBQ8ZQ1065L';
export const DESKTOP_STORE_URL = `https://apps.microsoft.com/detail/${DESKTOP_STORE_ID}`;

export const DESKTOP_TAG = `desktop-v${DESKTOP_VERSION}`;

const RELEASE_BASE = `https://github.com/jannskiee/floe/releases/download/${DESKTOP_TAG}`;

/** The NSIS installer (per-user, no admin prompt). The primary download. */
export const DESKTOP_SETUP_URL = `${RELEASE_BASE}/floe-desktop-setup-${DESKTOP_VERSION}.exe`;

/** The portable zip (floe-desktop.exe + LICENSE). */
export const DESKTOP_ZIP_URL = `${RELEASE_BASE}/floe-desktop-${DESKTOP_VERSION}-windows-amd64.zip`;

/** sha256sum-format checksums for both assets. */
export const DESKTOP_SHA_URL = `${RELEASE_BASE}/SHA256SUMS.txt`;

/**
 * What changed. The docs changelog, not the GitHub release page: that page's
 * body is generated by desktop-release.yml and is the same boilerplate every
 * time (asset names, SmartScreen guidance, checksum instructions), so a link
 * labelled "Release notes" pointing at it was a promise the page could not
 * keep. The assets and checksums it also carries already have their own rows
 * on /download.
 */
export const DESKTOP_RELEASE_NOTES_URL = 'https://www.floe.one/docs/changelog';

/** The GitHub release page for this tag, for anyone who wants the raw assets. */
export const DESKTOP_RELEASE_PAGE_URL = `https://github.com/jannskiee/floe/releases/tag/${DESKTOP_TAG}`;

/** Every release, desktop and CLI alike. */
export const ALL_RELEASES_URL = 'https://github.com/jannskiee/floe/releases';
