// Reading a room id out of a URL, validating it, and building the link that
// carries it. Pure by construction: every browser value is passed in, because
// client/vitest.config.ts runs with environment: 'node' and a module that read
// window here could not be tested at all, which was the point of moving it.

/** Room ids live in the URL fragment: fragments are never sent to the server,
 *  never appear in a Referer header, and are ignored by pageview analytics.
 *  Older links used the ?room=<id> query param, which leaked into all three,
 *  so those are still read for backward compatibility.
 *
 *  Takes hash and search rather than reading window, so the caller stays the
 *  only place that touches the DOM: getRoomFromUrl(location.hash, location.search). */
export function getRoomFromUrl(hash: string, search: string): string | null {
    const fromHash = new URLSearchParams(hash.replace(/^#/, '')).get('room');
    if (fromHash) return fromHash;
    return new URLSearchParams(search).get('room');
}

/** Mirrors the signaling server's UUID_REGEX (server/server.js) so the client
 *  rejects a malformed room id up front instead of emitting a join the server
 *  would refuse with an 'error' event the browser does not listen for.
 *
 *  Keep in sync with the server: a loose format check, not a version- or
 *  variant-strict UUID validation. Moving it here does NOT make it a shared
 *  source, because server/ is a separate CommonJS package; there are still two
 *  copies, and this is the one that now has a test. */
const ROOM_ID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isValidRoomId(roomId: string): boolean {
    return ROOM_ID_REGEX.test(roomId);
}

/** buildShareLink assembles the invitation URL.
 *
 *  The nonce is a per-link value in the QUERY string, not the fragment, and it
 *  is what makes every transfer link a distinct document. Without it two links
 *  differ only in the fragment, which browsers treat as the same page, so a
 *  phone that already has Floe open can reuse a stale tab when a new QR is
 *  scanned instead of joining the new room. The secret room id stays in the
 *  fragment and is never sent to the server; the nonce carries no information.
 *
 *  Both ids are generated by the caller. Passing them in rather than calling
 *  uuidv4 here is what makes the assembled string assertable. */
export function buildShareLink(origin: string, roomId: string, nonce: string): string {
    return `${origin}/?s=${nonce}#room=${roomId}`;
}
