// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EngineProtocolVersion():Promise<number>;

export function ReceiveByCode(arg1:string,arg2:string):Promise<string>;
