// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer() {
  return window['go']['main']['App']['CancelTransfer']();
}

export function ContextMenuEnabled() {
  return window['go']['main']['App']['ContextMenuEnabled']();
}

export function DisableContextMenu() {
  return window['go']['main']['App']['DisableContextMenu']();
}

export function EnableContextMenu() {
  return window['go']['main']['App']['EnableContextMenu']();
}

export function EngineProtocolVersion() {
  return window['go']['main']['App']['EngineProtocolVersion']();
}

export function GetPendingFiles() {
  return window['go']['main']['App']['GetPendingFiles']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PasteFiles() {
  return window['go']['main']['App']['PasteFiles']();
}

export function ReceiveByCode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReceiveByCode'](arg1, arg2, arg3, arg4);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartSend(arg1, arg2) {
  return window['go']['main']['App']['StartSend'](arg1, arg2);
}

export function StartSendText(arg1, arg2) {
  return window['go']['main']['App']['StartSendText'](arg1, arg2);
}
