// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer():Promise<void>;

export function EngineProtocolVersion():Promise<number>;

export function OpenFolder(arg1:string):Promise<void>;

export function ReceiveByCode(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function StartSend(arg1:Array<string>,arg2:boolean):Promise<void>;
